### PR TITLE
Roll 21 static db user info

### PR DESCRIPTION
**Pull request by brickgriff**
Connect and read static user entries from Firebase, as the first step to data management. Initially we'll be pulling down data from collections called `staticusers` and `staticcards`. Later, we will be able to pull information from the restricted collections when authentication is provided.

Currently we are only displaying a list of all data. Next step is to retrieve info from a single static user (as if it were logged in). This will allow us to simulate the following cycles:

- viewing/updating user profile
- viewing rolodex
- adding/removing a contact from the list of available users (not a contact nor the current user)
- CRUD a card (user-owned)
- viewing card (contact-owned)

### CODE REVIEW

**Comment by brickgriff** [comment]
Clean but do not merge this version, yet. I had to modify the project-lock.json file which is automatically generated. I will run `ng update --all --force; npm update; npm i` to update.

**Comment by brickgriff** [comment]
This version is okay to test and merge into `dev`.

**Review by brandlxee11 — APPROVED** [review]
-  In reference to the firestore.rules file, do we need to worry about the "app will lose access to your Firestore database" if security rules aren't written to "protect the app from [potential] attackers"? Just curious.

-  Also, the format for imports in the app in Ionic 4 ends with "ngx" like so:
   /import { SplashScreen } from '@ionic-native/splash-screen/ngx';
   Installation of Angular's infinite scroll that could possibly be used for the rolodex is "ngx-infinite- 
   scroll". Does this indicate compatibility and, thus, integration into the app?

**Comment by brandlxee11** [comment]
Just tested it out locally and runs fine!

**Pull request merged**
