### PR TITLE
Roll 17 data service

### PR DESCRIPTION
**Pull request by brickgriff**
https://github.com/bgriffiniv/rollme/issues/23

This fix basically demonstrates reading the user data from a service rather than an object that is only local to the profile page. This way, the true source of data can be hidden behind the data service, freeing the profile component to worry about navigating to/from the edit page and handling events fired by the router.

### CODE REVIEW

**Review by brandlxee11 — APPROVED** [review]
Looks good. And I see spec.ts files are created by Angular to run unit tests on source files. Cool.

**Comment by brickgriff** [comment]
> Looks good. And I see spec.ts files are created by Angular to run unit tests on source files. Cool.

Yes. We'll be filling these spec files and running Karma in no time.

**Review by Yogen1337 — APPROVED** [review]

**Comment by brandlxee11** [comment]
Burnest, I think you may need to resolve the conflicts to merge with dev.

**Comment by brandlxee11** [comment]
Nvm! I did it from my local and it merged!

**Pull request merged**
